---
name: Build cryptopp
description: Build and cache cryptopp libraries
inputs:
  version:
    description: The cryptopp version to build
    required: true
  architecture:
    description: The openssl architecture to build
    required: true
outputs:
  path:
    description: The path to the cryptopp folder
    value:  ${{ steps.path.outputs.path }}
  path_unix:
    description: The path to the cryptopp folder
    value:  ${{ steps.path.outputs.path_unix }}
runs:
  using: composite
  steps:

    - id: versions
      run: |
        $tag_version="${{ inputs.version }}".replace('.','_')
        $file_version="${{ inputs.version }}".replace('.','')
        echo "tag_version=$tag_version" >> $env:GITHUB_OUTPUT
        echo "file_version=$file_version" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Download
      run: |
            curl -L https://github.com/weidai11/cryptopp/releases/download/CRYPTOPP_${{ steps.versions.outputs.tag_version }}/cryptopp${{ steps.versions.outputs.file_version }}.zip --output cryptopp.zip
            mkdir cryptopp
            cd cryptopp
            7z x ..\cryptopp.zip
      working-directory: tmp
      shell: cmd

    - id: cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cryptopp-${{ inputs.version }}-${{ inputs.architecture }}
        path: |
          tmp/cryptopp/*/DLL_Output/Release

    - name: Build x86
      run: |
        python ../../build/python/msdev-to-dynamic.py cryptlib.vcxproj
        msbuild cryptlib.vcxproj /p:Configuration=Release /p:Platform=win32
        msbuild cryptlib.vcxproj /p:Configuration=Debug /p:Platform=win32
        msbuild cryptdll.vcxproj /p:Configuration=Release /p:Platform=win32
        msbuild cryptdll.vcxproj /p:Configuration=Debug /p:Platform=win32
        tree
      working-directory: tmp/cryptopp
      shell: cmd
      if: ${{ steps.cache.outputs.cache-hit != 'true' && inputs.architecture == 'x86' }}

    - name: Build x64
      run: |
        python ../../build/python/msdev-to-dynamic.py cryptlib.vcxproj
        msbuild cryptlib.vcxproj /p:Configuration=Release /p:Platform=x64
        msbuild cryptlib.vcxproj /p:Configuration=Debug /p:Platform=x64
        msbuild cryptdll.vcxproj /p:Configuration=Release /p:Platform=x64
        msbuild cryptdll.vcxproj /p:Configuration=Debug /p:Platform=x64
        tree
      working-directory: tmp/cryptopp
      shell: cmd
      if: ${{ steps.cache.outputs.cache-hit != 'true' && inputs.architecture == 'x64' }}

    - id: path
      run: |
        $path=$pwd.path
        $path_unix=$pwd.path.replace('\','/')
        echo "path=$path" >> $env:GITHUB_OUTPUT
        echo "path_unix=$path_unix" >> $env:GITHUB_OUTPUT
      shell: pwsh
      working-directory: tmp/cryptopp
