name: Build release

on:
  push:
    branches: [main]

jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
  build-x64:
    needs: get-version
    uses: ./.github/workflows/build-windows.yml
    with: 
      architecture: x64
      version: ${{ needs.get-version.outputs.version }}
  build-x86:
    needs: get-version
    uses: ./.github/workflows/build-windows.yml
    with: 
      architecture: x86
      version: ${{ needs.get-version.outputs.version }}

  release:
    needs: [get-version, build-x64, build-x86]
    uses: ./.github/workflows/release.yml
    with:
      version: ${{ needs.get-version.outputs.version }}