name: CMake

on:
  push: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Build Boost
      id: boost
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.79.0
        libraries: system filesystem thread regex date_time program_options python37 chrono
        platform: x64
        configuration: Release

    - name: Show paths
      run: |
        echo "${{ steps.boost.outputs.root }}"
        echo "${{ steps.boost.outputs.librarydir }}"
      shell: cmd